"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var seed_1 = require("@snaplet/seed");
// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed
var snaplet = new seed_1.SnapletClient({
    dryRun: process.env.DRY !== '0',
});
// Clears all existing data in the database, but keep the structure
await snaplet.$resetDatabase();
await snaplet.people(function (x) { return x(3); });
