create table main_capabilities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  deleted_at timestamp with time zone default timezone('utc'::text, now()),
  role_id bigint not null references roles,
  competence_id bigint not null references competences,
  task text,
  knowledge text,
  skill text,
  ability text
);

create extension if not exists moddatetime schema extensions;

-- assuming the table name is "todos", and a timestamp column "updated_at"
-- this trigger will set the "updated_at" column to the current timestamp for every update
create trigger
  handle_updated_at before update
on main_capabilities
for each row execute
  procedure moddatetime(updated_at);